version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./ibis_crawl_engine/conf/docker/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=ibis
      - POSGTGRES_PASSWORD=13635724
      - POSTGRES_DB=articles
    ports:
      - "5433:5432"