# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='source',
            field=models.CharField(default='google', help_text='Type please with 1 backspace and 1 coma btw words. Ex.: google, yahoo', max_length=200),
        ),
    ]
