# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0002_auto_20161104_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
