# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-19 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0004_auto_20161218_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='channel',
            field=models.CharField(choices=[('industry', 'Industry'), ('research', 'Research'), ('government', 'Government'), ('other', 'Other biointel'), ('search_engines', 'Search Engines'), ('social', 'Social'), ('general', 'General')], db_column='search_channel', default='general', max_length=64),
        ),
    ]
