# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0005_searchquery_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(blank=True, help_text='Type resource name only. E.g.: "wikipedia", "google"', max_length=124)),
            ],
        ),
    ]
