# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0006_auto_20160713_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_date_created',
            field=models.DateTimeField(blank=True),
        ),
    ]
