# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0008_auto_20160713_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_date_created',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
