# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0011_auto_20170415_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedsite',
            name='site',
            field=models.CharField(max_length=255),
        ),
    ]
