# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0015_auto_20160728_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='search_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
