# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0016_auto_20170510_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='top_image_processed',
            field=models.BooleanField(default=False),
        ),
    ]
