# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0016_article_search_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.UUIDField(db_index=True)),
                ('query', models.TextField()),
                ('source', models.CharField(choices=[('google', 'google'), ('bing', 'bing'), ('yandex', 'yandex')], default='google', max_length=15)),
                ('active', models.BooleanField(default=True)),
                ('period', models.CharField(choices=[('houlry', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
            ],
        ),
    ]
