# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0017_article_top_image_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='top_image_processed',
        ),
    ]
