# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0017_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='last_processed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
