# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0018_searchquery_last_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='last_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
