# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0020_auto_20160810_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='period',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='source',
            field=models.CharField(choices=[('google', 'Google'), ('bing', 'Bing'), ('yandex', 'Yandex')], default='google', max_length=15),
        ),
    ]
