# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0021_auto_20160811_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtask',
            name='search_query',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crawl_engine.SearchQuery'),
        ),
    ]
