# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0022_auto_20160811_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchtask',
            name='last_run',
        ),
    ]
