# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0025_auto_20160811_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
