# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0032_auto_20160826_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='translated_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
