# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0033_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='meta_info',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='translated_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
