# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0036_auto_20160902_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='rss_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='search_type',
            field=models.CharField(blank=True, choices=[('search_engine', 'Search Engine'), ('rss', 'RSS Feed'), ('email', 'Email')], default='search_engine', max_length=20, null=True),
        ),
    ]
