# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0040_auto_20160921_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='article_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
