# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0042_auto_20160929_1432'),
        ('crawl_engine', '0043_auto_20160928_0857'),
    ]

    operations = [
    ]
