# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0045_auto_20160930_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='response_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
