# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 19:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0056_auto_20161103_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='source',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='google'),
        ),
    ]
