# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0057_auto_20161103_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='source',
            field=models.CharField(choices=[('google', 'Google'), ('google_cse', 'Google CSE'), ('google_blogs', 'Google Blogs'), ('google_news', 'Google News'), ('google_scholar', 'Google Scholar')], default='google', max_length=15),
        ),
    ]
