# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0058_auto_20161103_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='source',
            field=models.CharField(default='google', max_length=200),
        ),
    ]
