# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0059_auto_20161103_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='source',
            field=models.CharField(default='google', help_text='Type please with 1 backspace and 1 coma btw words. Ex.: google, yahoo', max_length=200),
        ),
    ]
