# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0033_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='meta_info',
        ),
    ]
