# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0031_auto_20160811_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='source',
            field=models.CharField(choices=[('google', 'Google'), ('google_cse', 'Google CSE'), ('bing', 'Bing'), ('yandex', 'Yandex')], default='google', max_length=15),
        ),
    ]
