# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0031_auto_20160811_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='search_id',
        ),
        migrations.AddField(
            model_name='article',
            name='search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crawl_engine.SearchQuery'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='search_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='source',
            field=models.CharField(choices=[('google', 'Google'), ('google_cse', 'Google CSE'), ('bing', 'Bing'), ('yandex', 'Yandex')], default='google', max_length=15),
        ),
    ]
