# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0032_auto_20160819_1453'),
        ('crawl_engine', '0032_auto_20160819_1409'),
    ]

    operations = [
    ]
