# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 07:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('crawl_engine', '0001_initial'), ('crawl_engine', '0002_task'), ('crawl_engine', '0003_auto_20160713_1342'), ('crawl_engine', '0004_auto_20160713_1417'), ('crawl_engine', '0005_auto_20160713_1436'), ('crawl_engine', '0006_auto_20160713_1440'), ('crawl_engine', '0007_auto_20160713_1454'), ('crawl_engine', '0008_auto_20160713_1456'), ('crawl_engine', '0009_auto_20160718_0640'), ('crawl_engine', '0010_auto_20160719_1117'), ('crawl_engine', '0011_auto_20160719_1251'), ('crawl_engine', '0012_auto_20160720_1026'), ('crawl_engine', '0013_article_top_image_url'), ('crawl_engine', '0014_article_source_language'), ('crawl_engine', '0015_auto_20160728_1150'), ('crawl_engine', '0016_article_search_id'), ('crawl_engine', '0017_searchquery'), ('crawl_engine', '0018_searchquery_last_processed'), ('crawl_engine', '0019_auto_20160809_1443'), ('crawl_engine', '0020_auto_20160810_1354'), ('crawl_engine', '0021_auto_20160811_1019'), ('crawl_engine', '0022_auto_20160811_1207'), ('crawl_engine', '0023_remove_searchtask_last_run'), ('crawl_engine', '0024_auto_20160811_1309'), ('crawl_engine', '0025_auto_20160811_1317'), ('crawl_engine', '0026_delete_task'), ('crawl_engine', '0027_auto_20160811_1321'), ('crawl_engine', '0028_auto_20160811_1322'), ('crawl_engine', '0029_auto_20160811_1330'), ('crawl_engine', '0030_auto_20160811_1404'), ('crawl_engine', '0031_auto_20160811_1405'), ('crawl_engine', '0032_auto_20160826_1405'), ('crawl_engine', '0033_auto_20160826_1417'), ('crawl_engine', '0034_auto_20160831_1251'), ('crawl_engine', '0035_searchquery_options'), ('crawl_engine', '0036_auto_20160902_0832'), ('crawl_engine', '0037_auto_20160902_1415'), ('crawl_engine', '0038_auto_20160913_0909'), ('crawl_engine', '0039_auto_20160919_1400'), ('crawl_engine', '0040_auto_20160921_1203'), ('crawl_engine', '0041_searchquery_article_url'), ('crawl_engine', '0042_article_processed'), ('crawl_engine', '0043_auto_20160928_0857'), ('crawl_engine', '0042_auto_20160929_1432'), ('crawl_engine', '0044_merge_20160930_0807'), ('crawl_engine', '0045_auto_20160930_0909'), ('crawl_engine', '0046_searchquery_response_address'), ('crawl_engine', '0047_auto_20161005_1555'), ('crawl_engine', '0048_auto_20161006_1443'), ('crawl_engine', '0049_auto_20161007_1215'), ('crawl_engine', '0050_auto_20161011_1455'), ('crawl_engine', '0051_article_file'), ('crawl_engine', '0052_auto_20161103_1727'), ('crawl_engine', '0053_auto_20161103_1729'), ('crawl_engine', '0054_auto_20161103_1732'), ('crawl_engine', '0055_auto_20161103_1754'), ('crawl_engine', '0056_auto_20161103_1800'), ('crawl_engine', '0057_auto_20161103_1900'), ('crawl_engine', '0058_auto_20161103_1930'), ('crawl_engine', '0059_auto_20161103_1935'), ('crawl_engine', '0060_auto_20161103_2052')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date_crawled', models.DateTimeField(auto_now_add=True, null=True)),
                ('article_url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=240)),
                ('body', models.TextField(blank=True)),
                ('authors', models.CharField(blank=True, max_length=240)),
                ('post_date_created', models.CharField(blank=True, max_length=50)),
                ('translated', models.BooleanField(default=False)),
                ('translated_body', models.TextField(blank=True)),
                ('translated_title', models.CharField(blank=True, max_length=240)),
                ('top_image', models.ImageField(blank=True, null=True, upload_to='article-images')),
                ('top_image_url', models.URLField(blank=True)),
                ('source_language', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.CharField(db_index=True, max_length=50)),
                ('query', models.TextField(blank=True)),
                ('source', models.CharField(default='google', help_text='Type please with 1 backspace and 1 coma btw words. Ex.: google, yahoo', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('last_processed', models.DateTimeField(blank=True, null=True)),
                ('search_depth', models.PositiveIntegerField(default=10)),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('rss_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('search_type', models.CharField(choices=[('simple_search', 'Simple Search'), ('search_engine', 'Search Engine'), ('rss', 'RSS Feed'), ('article', 'Article'), ('email', 'Email')], default='search_engine', max_length=20)),
                ('article_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('response_address', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTask',
            fields=[
                ('task_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('search_query', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crawl_engine.SearchQuery')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crawl_engine.SearchQuery'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='translated_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='top_image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='top_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='article-images'),
        ),
        migrations.AddField(
            model_name='article',
            name='processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='pushed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='translated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_url',
            field=models.URLField(db_index=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='article-files'),
        ),
    ]
