# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date_crawled', models.DateField(auto_created=True)),
                ('article_url', models.URLField()),
                ('title', models.CharField(max_length=240)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=240)),
                ('post_date_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='/article-images')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl_engine.Article')),
            ],
        ),
    ]
