# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0009_auto_20160718_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='translated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='translated_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='translated_title',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
