# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0010_auto_20160719_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimages',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='top_image',
            field=models.ImageField(blank=True, null=True, upload_to='/article-images'),
        ),
        migrations.DeleteModel(
            name='ArticleImages',
        ),
    ]
