# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0011_auto_20160719_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='top_image',
            field=models.ImageField(blank=True, null=True, upload_to='article-images'),
        ),
    ]
