# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0012_auto_20160720_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='top_image_url',
            field=models.URLField(blank=True),
        ),
    ]
