# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0013_article_top_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_language',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
