# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0019_auto_20160809_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTask',
            fields=[
                ('task_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('last_run', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='searchquery',
            name='search_depth',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='searchtask',
            name='search_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl_engine.SearchQuery'),
        ),
    ]
