# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0023_remove_searchtask_last_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='search_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
