# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0026_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='search_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crawl_engine.SearchQuery'),
        ),
    ]
