# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0028_auto_20160811_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_date_crawled',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
