# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 14:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0034_auto_20160831_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
