# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0037_auto_20160902_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='search_type',
            field=models.CharField(blank=True, choices=[('search_engine', 'Search Engine'), ('rss', 'RSS Feed'), ('email', 'Email')], default='search_engine', max_length=20),
        ),
    ]
