# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0039_auto_20160919_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='query',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='search_type',
            field=models.CharField(choices=[('search_engine', 'Search Engine'), ('rss', 'RSS Feed'), ('article', 'Article'), ('email', 'Email')], default='search_engine', max_length=20),
        ),
    ]
