# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0041_searchquery_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='search_type',
            field=models.CharField(choices=[('simple_search', 'Simple Search'), ('search_engine', 'Search Engine'), ('rss', 'RSS Feed'), ('article', 'Article'), ('email', 'Email')], default='search_engine', max_length=20),
        ),
    ]
