# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0041_searchquery_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
