# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0042_article_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pushed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='translated',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
