# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0044_merge_20160930_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='search_depth',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
