# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0046_searchquery_response_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='search_depth',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
