# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_engine', '0050_auto_20161011_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='article-files'),
        ),
    ]
